"""add lectures table

Revision ID: c58ded1000f2
Revises: a44d67a0fd85
Create Date: 2026-05-31 15:34:14.207390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c58ded1000f2'
down_revision: Union[str, None] = 'a44d67a0fd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('session_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_richtext', sa.Text(), nullable=True),
    sa.Column('slides_json', sa.JSON(), nullable=False),
    sa.Column('clo_codes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectures')
    # ### end Alembic commands ###
