"""add clo description_en

Revision ID: cff274f4d9b9
Revises: 8420f220f490
Create Date: 2026-05-31 05:15:40.289546
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cff274f4d9b9'
down_revision: Union[str, None] = '8420f220f490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clos', schema=None) as batch_op:
        batch_op.drop_column('description_en')

    # ### end Alembic commands ###
